language: go
go:
- "1.16.x"
- tip
matrix:
    fast_finish: true
    allow_failures:
    - go: tip
env:
  secure: "cgpnkmmHixR8jAwzO8MizqVUGK7GgWu27syhnnGtI2714JhH4ubuNguNn1St/m8tAmZFOeQmh4qmxRNLi6fNnHb1mOsavqrJr0kyZYADf5zz6fn03yEqzYIaNL0j6iuBin0XMJbfsxyR5tCGllCPm97CpXIF16GeJSbsY8B0Jts="
addons:
  apt:
    packages:
    - libtagc0
    - libtagc0-dev
sudo: false
before_install:
- curl -sLOf https://raw.githubusercontent.com/MStoykov/fmtpolice/master/fmtpolice
- curl -sLOf https://raw.githubusercontent.com/MStoykov/fmtpolice/master/coverage
- go get github.com/axw/gocov/gocov github.com/mattn/goveralls
- go get golang.org/x/tools/cmd/cover
- go get github.com/golang/lint/golint
- go get -t -v $(go list ./... | grep -v '/vendor/')
before_script:
- bash fmtpolice
- go vet $(go list ./... | grep -v '/vendor/')
- go generate $(go list ./... | grep -v '/vendor/')
- test -z `git diff`
script:
- bash coverage -v
after_script:
- "$HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service=travis-ci"
